### PR TITLE
Ag 8

### PR DESCRIPTION
**Pull request by abelgoodwin1988**
Ref #8 #9 

Mock forms with no data backing. 
Will create another issue to refactor some items to simplify codebase.

### CODE REVIEW

**Comment by abelgoodwin1988** [comment]
Made some changes here. Changes the .gitconfig to not ignore case-sensitivity. Formatting for eslint.

**Comment by Maxbrain0** [comment]
Fails for me. 

Relative modules are not found.
image

I don't see /components/audtions/LambOfGod.vue in my file structure.
Also it is not finding /components/audtions/ColoradoMormonChorale.vue (probably because of capitalization error in file.

image

**Comment by abelgoodwin1988** [comment]
Sorry about that, how about now @Maxbrain0 ? I updated and it shows the appropriate file capitalization on my end and in the github repo.

Looks like in the github repo, however has a lower-case file for coloradomormonchorale which we should delete.

**Comment by abelgoodwin1988** [comment]
uhhh, I do have eslint installed/running.. what the heck.
I'm fine keeping it; it's an environment issue. I went through any linting issues I saw and didn't have any, so it's something on my end.

**Comment by abelgoodwin1988** [comment]
```json
"eslint.validate": [
        "javascript",
        "javascriptreact",
        { "language": "vue", "autoFix": false}
    ]
```
@Maxbrain0 
Fixed the issue; my eslint wasn't configured to lint vue files, so I had to add a language to it.

I think I've cleared up the linting.

With regards to moving away from airbnb; I think we should keep it. It will remind us as we build to keep our code concise and in best practices. It will be a pain, but it's really generally small syntactical fixes and spaces.

**Comment by Maxbrain0** [comment]
Looks good now! Glad you got your linting config to work!

I hope it was at least showing in Vue-CLI compiling. But maybe not.

**Pull request merged**
